version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 21

.move
    h q[12]
    h q[13]
    h q[14]
    x q[0]
    toffoli q[0],q[12],q[18]
    cnot q[0],q[12]
    toffoli q[12],q[15],q[18]
    cnot q[12],q[15]
    cnot q[0],q[12]
    toffoli q[18],q[13],q[19]
    cnot q[18],q[13]
    toffoli q[13],q[16],q[19]
    cnot q[13],q[16]
    cnot q[18],q[13]
    toffoli q[19],q[14],q[20]
    cnot q[19],q[14]
    toffoli q[14],q[17],q[20]
    cnot q[14],q[17]
    cnot q[19],q[14]
    prep_z q[18]
    prep_z q[19]
    prep_z q[20]
