version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 10

.init
    prep_z q[4]
    prep_z q[5]
    prep_z q[6]
    prep_z q[7]
    prep_z q[8]
    prep_z q[9]
    x q[4]
    prep_z q[0]
    prep_z q[1]
    prep_z q[2]
    prep_z q[3]

.read
    toffoli q[0],q[1],q[3]
    toffoli q[2],q[3],q[4]
    toffoli q[0],q[1],q[3]
    toffoli q[2],q[3],q[4]
