version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 25
.init

    { x q[0] | x q[1] | x q[2] | x q[3] | x q[4] | x q[5] }
    wait 1

.read

    { x q[8] | x q[9] | x q[10] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[13],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[13],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[13],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[13],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 3
    { x q[8] | x q[9] }
    wait 1
    { x q[10] | x q[8] | x q[9] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[14],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[14],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[14],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[14],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 3
    x q[8]
    wait 1
    { x q[9] | x q[8] | x q[10] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[15],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[15],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[15],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[15],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 3
    x q[8]
    wait 1
    { x q[10] | x q[8] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[16],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[16],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[16],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[16],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 5
    { x q[8] | x q[9] | x q[10] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[17],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[17],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[17],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[17],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 3
    x q[9]
    wait 1
    { x q[10] | x q[9] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[18],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[18],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[18],q[1] }
    wait 7
    toffoli q[19],q[1],q[11]
    wait 7
    toffoli q[10],q[18],q[1]
    wait 7
    toffoli q[19],q[1],q[11]
    wait 5
    x q[9]
    wait 1

.fsm

    x q[6]
    wait 1
    toffoli q[6],q[0],q[19]
    wait 5
    x q[11]
    wait 1
    toffoli q[11],q[19],q[20]
    wait 7
    toffoli q[6],q[0],q[19]
    wait 7
    toffoli q[11],q[19],q[20]
    wait 7
    toffoli q[6],q[1],q[19]
    wait 7
    toffoli q[11],q[19],q[12]
    wait 7
    toffoli q[6],q[1],q[19]
    wait 7
    toffoli q[11],q[19],q[12]
    wait 7
    toffoli q[6],q[2],q[19]
    wait 7
    toffoli q[11],q[19],q[7]
    wait 7
    toffoli q[6],q[2],q[19]
    wait 7
    toffoli q[11],q[19],q[7]
    wait 7
    toffoli q[6],q[3],q[19]
    wait 5
    x q[11]
    wait 1
    toffoli q[11],q[19],q[20]
    wait 7
    toffoli q[6],q[3],q[19]
    wait 7
    toffoli q[11],q[19],q[20]
    wait 7
    toffoli q[6],q[4],q[19]
    wait 7
    toffoli q[11],q[19],q[12]
    wait 7
    toffoli q[6],q[4],q[19]
    wait 7
    toffoli q[11],q[19],q[12]
    wait 7
    toffoli q[6],q[5],q[19]
    wait 7
    toffoli q[11],q[19],q[7]
    wait 7
    toffoli q[6],q[5],q[19]
    wait 7
    toffoli q[11],q[19],q[7]
    wait 5
    x q[6]
    wait 1

.write

    { x q[8] | x q[9] | x q[10] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[13]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[13]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[13]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[13]
    wait 3
    { x q[8] | x q[9] }
    wait 1
    { x q[10] | x q[8] | x q[9] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[14]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[14]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[14]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[14]
    wait 3
    x q[8]
    wait 1
    { x q[9] | x q[8] | x q[10] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[15]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[15]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[15]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[15]
    wait 3
    x q[8]
    wait 1
    { x q[10] | x q[8] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[16]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[16]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[16]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[16]
    wait 5
    { x q[8] | x q[9] | x q[10] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[17]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[17]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[17]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[17]
    wait 3
    x q[9]
    wait 1
    { x q[10] | x q[9] }
    wait 1
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[18]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[18]
    wait 7
    { toffoli q[8],q[9],q[19] | toffoli q[10],q[12],q[1] }
    wait 7
    toffoli q[19],q[1],q[18]
    wait 7
    toffoli q[10],q[12],q[1]
    wait 7
    toffoli q[19],q[1],q[18]
    wait 5
    x q[9]
    wait 1

.move

    toffoli q[7],q[8],q[22]
    wait 3
    toffoli q[22],q[9],q[23]
    wait 3
    cnot q[23],q[10]
    wait 3
    { cnot q[7],q[8] | toffoli q[22],q[9],q[23] }
    wait 3
    { cnot q[22],q[9] | cnot q[7],q[8] }
    wait 3
    toffoli q[7],q[8],q[22]
    wait 3
    cnot q[7],q[8]
    wait 3
    x q[7]
    wait 1
    x q[7]
    wait 1

