version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 18

.move
    h q[1]
    h q[2]
    h q[3]
    cnot q[1],q[15]
    cnot q[2],q[16]
    cnot q[3],q[17]
    x q[0]
    toffoli q[0],q[1],q[12]
    cnot q[0],q[1]
    toffoli q[12],q[2],q[13]
    cnot q[13],q[3]
    toffoli q[12],q[2],q[13]
    cnot q[12],q[2]
    cnot q[0],q[1]
    toffoli q[0],q[1],q[12]
    cnot q[0],q[1]
    x q[0]
