version 1.0
# this file has been automatically generated by the OpenQL compiler please do not modify it manually.
qubits 18
.move

    h q[1]
    wait 1
    cnot q[1],q[15]
    wait 1
    { h q[2] | x q[0] }
    wait 1
    { cnot q[2],q[16] | toffoli q[0],q[1],q[12] }
    wait 1
    h q[3]
    wait 1
    { cnot q[3],q[17] | toffoli q[12],q[2],q[13] }
    wait 3
    cnot q[13],q[3]
    wait 3
    { cnot q[0],q[1] | toffoli q[12],q[2],q[13] }
    wait 3
    { cnot q[12],q[2] | cnot q[0],q[1] }
    wait 3
    toffoli q[0],q[1],q[12]
    wait 3
    cnot q[0],q[1]
    wait 3
    x q[0]
    wait 1

